// tmp/webportal/src/components/Address.tsx
import { Component, createEffect, createSignal } from 'solid-js';
import { useNavigate, useSearchParams } from '@solidjs/router';
import { searchAddresses, type AddressData } from '../lib/data';

const Address: Component = () => {
	const navigate = useNavigate();
	const [searchParams] = useSearchParams();
	const [query, setQuery] = createSignal('');
	const [matches, setMatches] = createSignal<AddressData[]>([]);

	createEffect(() => {
		const q = searchParams.q || '';
		setQuery(q);
		setMatches(searchAddresses(q));
	});

	const selectAddress = (addr: string) => {
		navigate(`/result?addr=${encodeURIComponent(addr)}`);
	};

	return (
		<div class="min-h-screen bg-gray-50 py-8">
			<div class="max-w-2xl mx-auto bg-white shadow-lg rounded-lg p-8">
				{matches().length === 0 ? (
					<>
						<p class="text-red-600 mb-4">Keine passende Adresse gefunden für "{query()}". Bitte überprüfen Sie die Eingabe oder versuchen Sie eine andere Adresse.</p>
						<a href="/" class="text-blue-600 hover:text-blue-800 underline">Zurück zur Suche</a>
					</>
				) : matches().length === 1 ? (
					<>
						{/* Redirect */}
						{(() => {
							navigate(`/result?addr=${encodeURIComponent(matches()[0].original)}`);
							return null;
						})()}
					</>
				) : (
					<>
						<h1 class="text-2xl font-bold text-gray-900 mb-4">Mögliche Adressen oder Flurstücke für: {query()}</h1>
						<p class="text-gray-600 mb-6">Wählen Sie die passende Adresse aus, um die relevanten Dokumente und den Chatbot zu öffnen.</p>
						<ul class="space-y-2 mb-6">
							{matches().map((match) => (
								<li>
									<button
										onClick={() => selectAddress(match.original)}
										class="w-full text-left px-4 py-2 bg-blue-50 hover:bg-blue-100 border border-blue-200 rounded-md transition-colors"
									>
										{match.original}
									</button>
								</li>
							))}
						</ul>
						<a href="/" class="text-blue-600 hover:text-blue-800 underline">Zurück zur Suche</a>
					</>
				)}
			</div>
		</div>
	);
};

export default Address;

// services/frontend/apps/chat-app/src/portal/Address.vue
<script setup lang="ts">
import { searchAddresses, type AddressData } from '@shared/portal-address';
import { computed, onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';

const route = useRoute();
const router = useRouter();

const query = ref<string>('');
const matches = ref<AddressData[]>([]);

const hasNoMatches = computed(() => matches.value.length === 0);
const hasOneMatch = computed(() => matches.value.length === 1);

function runSearch(q: string) {
  query.value = q;
  matches.value = q ? searchAddresses(q) : [];
}

function selectAddress(addr: string) {
  router.push({ name: 'chat', query: { addr } });
}

onMounted(() => {
  const q = (route.query.q as string) || '';
  runSearch(q);
});

watch(
  () => route.query.q,
  (newQ: unknown) => runSearch((newQ as string) || '')
);

watch(
  () => matches.value,
  (vals: AddressData[]) => {
    if (vals.length === 1) {
      selectAddress(vals[0].original);
    }
  }
);
</script>

<template>
  <div class="min-h-screen bg-base-100 py-8">
    <div class="max-w-2xl mx-auto bg-base-200 shadow rounded-box p-8">
      <template v-if="hasNoMatches">
  <p class="text-error mb-4">Keine passende Adresse gefunden für "{{ query }}". Bitte überprüfen Sie die Eingabe oder versuchen Sie eine andere Adresse.</p>
  <RouterLink :to="{ name: 'portal-home' }" class="link link-accent">Zurück zur Suche</RouterLink>
      </template>
      <template v-else-if="hasOneMatch">
        <p>Weiterleitung…</p>
      </template>
      <template v-else>
        <h1 class="text-2xl font-bold mb-4">Mögliche Adressen oder Flurstücke für: {{ query }}</h1>
        <p class="opacity-80 mb-6">Wählen Sie die passende Adresse aus, um die relevanten Dokumente und den Chatbot zu öffnen.</p>
        <ul class="space-y-2 mb-6">
          <li v-for="m in matches" :key="m.original">
            <button @click="selectAddress(m.original)" class="btn btn-outline btn-accent w-full justify-start">
              {{ m.original }}
            </button>
          </li>
        </ul>
        <RouterLink :to="{ name: 'portal-home' }" class="link link-accent">Zurück zur Suche</RouterLink>
      </template>
    </div>
  </div>

</template>
