// tmp/webportal/src/components/Home.tsx
import { Component, createSignal } from 'solid-js';
import { useNavigate } from '@solidjs/router';

const Home: Component = () => {
	const navigate = useNavigate();
	const [address, setAddress] = createSignal('');

	const handleSubmit = (e: Event) => {
		e.preventDefault();
		if (address().trim()) {
			navigate(`/address?q=${encodeURIComponent(address())}`);
		}
	};

	return (
		<div class="min-h-screen bg-gray-50 flex items-center justify-center">
			<div class="max-w-md w-full bg-white shadow-lg rounded-lg p-8">
				<h1 class="text-2xl font-bold text-gray-900 mb-4 text-center">Informationsportal der Unteren Bauaufsichtsbehörden des Saarlandes</h1>
				<p class="text-gray-600 mb-6 text-center">Geben Sie eine Adresse oder Flurstücknummer ein, um relevante Bauvorschriften und Bebauungspläne abzurufen und Fragen zu stellen.</p>
				<form onSubmit={handleSubmit} class="space-y-4">
					<div>
						<label for="address" class="block text-sm font-medium text-gray-700 mb-2">Adresse oder Flurstücknummer eingeben:</label>
						<input
							type="text"
							id="address"
							value={address()}
							onInput={(e) => setAddress(e.currentTarget.value)}
							placeholder="z.B. Saarbrücken, Markt 1 oder 1234/567"
							class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
							required
						/>
					</div>
					<button type="submit" class="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">
						Adresse prüfen
					</button>
				</form>
			</div>
		</div>
	);
};

export default Home;

// services/frontend/apps/chat-app/src/portal/Home.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();
const address = ref('');

function handleSubmit(e: Event) {
  e.preventDefault();
  const q = address.value?.trim();
  if (q) {
    router.push({ name: 'portal-address', query: { q } });
  }
}
</script>

<template>
  <div class="min-h-screen bg-base-100 flex items-center justify-center">
    <div class="max-w-xl w-full bg-base-200 shadow rounded-box p-8">
      <h1 class="text-2xl font-bold mb-4 text-center">
        Informationsportal der Unteren Bauaufsichtsbehörden des Saarlandes
      </h1>
      <p class="opacity-80 mb-6 text-center">
        Geben Sie eine Adresse oder Flurstücknummer ein, um relevante Bauvorschriften und Bebauungspläne abzurufen und Fragen zu stellen.
      </p>
      <form @submit="handleSubmit" class="space-y-4">
        <div>
          <label for="address" class="block text-sm font-medium mb-2">Adresse oder Flurstücknummer eingeben:</label>
          <input
            id="address"
            v-model="address"
            type="text"
            placeholder="z.B. Saarbrücken, Markt 1 oder 1234/567"
            required
            class="input input-bordered w-full"
          />
        </div>
        <button type="submit" class="btn btn-primary w-full">Adresse prüfen</button>
      </form>
    </div>
  </div>
</template>
